name: flask-ecr-eks-starter

services:
  web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
    image: yourapp/web:${TAG:-dev}
    env_file:
      - ./.env.dev
    environment:
      - PYTHONPATH=/
      # If you prefer to keep these out of .env.dev, uncomment the next lines:
      # - EMAIL_MODE=smtp
      # - SMTP_HOST=mailhog
      # - SMTP_PORT=1025
      # - SMTP_TLS=false
      # - EMAIL_SENDER=noreply@example.com
    depends_on:
      - db
      - redis
      - mailhog
    ports:
      - "${WEB_PORT:-8000}:8000"
    volumes:
      - ../app:/app:cached
      - ../docker/gunicorn_conf.py:/etc/gunicorn/gunicorn_conf.py:ro
    command: >
      sh -c "gunicorn app.wsgi:app -c /etc/gunicorn/gunicorn_conf.py"

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    image: yourapp/frontend:${TAG:-latest}
    depends_on:
      - web
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_API_ORIGIN=http://web:8000

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"   # UI at http://localhost:8025
      - "1025:1025"   # SMTP

volumes:
  pgdata:
  redisdata:
